; nidmi-player : lecteur MIDI (.mid) via nidmi-core

[platformio]
default_envs = esp32-s3-devkitc-1

[env]
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
extra_scripts =
  pre:${PROJECT_DIR}/../nidmi-core/scripts/pio_osc_disable_bluetooth_slip.py
lib_extra_dirs =
  ${PROJECT_DIR}/../nidmi-core
  ${PROJECT_DIR}/../nidmi-sequencer-core
lib_deps =
  fortyseveneffects/MIDI Library@5.0.2
  AppleMIDI
  cnmat/OSC@1.0.0

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
